version: '3'
services:
  mate-desktop-lmu:
    shm_size: "2gb"
    environment:
    - USER={{ USERNAME }}
    - PASSWORD={{ PASSWORD }}
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/debian-arm64-mate:bullseye
    restart: always
    stdin_open: true
    tty: true
    ports:
    - {{ NOMACHINE_PORT }}:4000/tcp
    - {{ X2GO_PORT }}:22/TCP
