version: '3'
services:
  mate-desktop-lmu:
    shm_size: "2gb"
    environment:
    - USER=mate
    - PASSWORD=mate
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/debian-mate-desktop:latest-arm64
    restart: always
    stdin_open: true
    tty: true
    ports:
    - 4001:4000/tcp
